# Build Anroid application
name: Android

on:
  push:
    branches:
      # - main
      # - dev
      - android

  workflow_dispatch:

jobs:
  android:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version: x.y.z
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      # Build
      - run: flutter --version
      - run: flutter pub get
      - run: make build-apk
      - run: make build-appbundle
      # Distribution
      - name: Upload artifact to Firebase App Distribution
        continue-on-error: true
        run: |
          firebase appdistribution:distribute \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
            --groups "${{ secrets.FIREBASE_TESTER_GROUPS }}" \
            build/app/outputs/apk/release/app-release.apk

      # - name: Upload to Google Play
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      #     packageName: freemind.app.test
      #     releaseFiles: app/build/outputs/bundle/release/app-release.aab
      #     track: internal
      #     status: draft
      #     # whatsNewDirectory: distribution/whatsnew
      #     # mappingFile: app/build/outputs/mapping/release/mapping.txt
      #     # debugSymbols: app/intermediates/merged_native_libs/release/out/lib
