# Build iOS application
name: iOS

on:
  push:
    branches:
      # - main
      # - dev
      - ios

  workflow_dispatch:

jobs:
  android:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version: x.y.z
      # Build
      - run: flutter --version
      - run: flutter pub get
      - run: make build-ipa
      # Distribution
      - name: Upload artifact to Firebase App Distribution
        continue-on-error: true
        run: |
          firebase appdistribution:distribute \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --app ${{ secrets.FIREBASE_IOS_APP_ID }} \
            --groups "${{ secrets.FIREBASE_TESTER_GROUPS }}" \
            build/app/outputs/apk/release/app-release.apk
      # Upload to Apple's TestFlight
      # https://github.com/marketplace/actions/upload-app-to-testflight
      # - name: "Upload app to TestFlight"
      #   uses: apple-actions/upload-testflight-build@v1
      #   with:
      #     app-path: build/ios/ipa/ComNet.ipa
      #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
      #     api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
