# Build Windows application
name: Windows

on:
  push:
    branches:
      # - main
      # - dev
      - windows

  workflow_dispatch:

jobs:
  windows:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version: x.y.z
      - run: flutter --version
      - run: make init
      - run: flutter pub get
      - run: make build
