#
# Code generated by `gkgen`
#

# Environments
-include .env

define get_config
$(shell yq -r ".$1" .config/service.base.yaml)
endef

define get_pubspec
$(shell yq -r ".$1" pubspec.yaml)
endef

# Service
NAME			= $(call get_config,name)
VERSION			= $(call get_pubspec,version)
DESCRIPTION		= $(call get_pubspec,description)
ARCH			?= amd64

# Registry
REGISTRY			?= registry.gitlab.com
REGISTRY_REPO		?= free-mind/hub
DOCKERFILE			?= Dockerfile

# Override the image & the helm package names
RELEASE_NAME		= $(NAME)

DEPLOYMENT_KIND		?= $(call get_yaml,deployment.kind,k8s)
HELM_REPO			?= freemind
HELM_NAMESPACE		?= dev

# Default platform
PLATFORM		?= $(shell uname | tr A-Z a-z)

ifeq ($(PLATFORM), darwin)
	PLATFORM	= macos
endif

# Flutter build flags
SERVICE_HOST	?= happymind.freemind.vn
SERVICE_PORT	?= 443

F_FLAGS			?= --dart-define=SERVICE_HOST=$(SERVICE_HOST) \
	--dart-define SERVICE_PORT=$(SERVICE_PORT) \
	--dart-define VERSION='$(VERSION)' \
	--dart-define BRANCH=$(shell git rev-parse --abbrev-ref HEAD) \
	--dart-define HASH=$(shell git rev-parse --short HEAD)

#: list all targets
help:
	@grep -B1 -E "^[a-zA-Z0-9_%-]+:([^\=]|$$)" Makefile \
		| grep -v -- -- \
		| sed 'N;s/\n/###/' \
		| sed -n 's/^#: \(.*\)###\(.*\):.*/\2###\1/p' \
		| column -t -s '###'

#: remove untracked files from the working tree
clean:
#	git clean -fdx
	gkgen clean $(arg)
	flutter clean

# -----------------------------------------------------------------------------
# Flutter
# -----------------------------------------------------------------------------

#: install necessary packages
init:
	dart pub global activate dartdoc
	dart pub global activate index_generator
	dart pub global activate arb_excel
	dart pub global activate import_sorter
	dart pub global activate protoc_plugin
	dart pub global activate flutterfire_cli

#: code formatting
fmt:
	dart pub global run import_sorter:main --no-comments
	dart pub global run index_generator
	dart fix --apply
	dart format --fix lib/src/

#: analyzes the project's Dart source code
lint:
	dart analyze lib/src/

#: generate l10n from 'assets/l10n/app.xlsx'
text:
	curl -Lo assets/l10n/app.xlsx 'https://onedrive.live.com/download?cid=681330426B4177E7&resid=681330426B4177E7%21116603&authkey=AEteDTs04X0cW9U&em=2'
	dart pub global run arb_excel -a assets/l10n/app.xlsx

#: creates API reference documentation from Dart source code
doc:
	@echo "• $(shell git rev-parse --short HEAD)-$(shell git rev-parse --abbrev-ref HEAD) • $(shell date "+%Y-%m-%d %H:%M")" > doc/api/footer
	dart doc

	@sed -i 's/<title>app - Dart API docs<\/title>/<title>$(NAME)<\/title>/' doc/api/index.html
	@sed -i 's/app package/Game Dashboard/' doc/api/index.html
	@sed -i 's/>app</>Game Dashboard</' doc/api/index.html
	@sed -En 's/<span class="no-break">.*<\/span>/<span class="no-break">Game Dasboard • $(gitCommit) • $(gitBranch) <\/span>/' doc/api/index.html

#: flutter test
test:
	flutter test --coverage  --coverage-path test/lcov.info

#: run your Flutter app on $(PLATFORM)
run:
	flutter run -d $(PLATFORM) $(F_FLAGS)

#: start DevTools 
dev:
	dart devtools

#: Build your Flutter app on $(PLATFORM)
build:
	@echo Build for $(PLATFORM)
	@make -s build-$(PLATFORM)

#: Run your Flutter on a platform: web, windows, linux, macos, android, ios
run-%:
	@echo "Building on: $*"
	flutter run -d $* $(F_FLAGS)

#: Build your Flutter app on a platform: web, windows, linux, macos, apk, appbundle, ios, ipa
build-%:
	@echo "Building on: $*"
	@if [ "$*" = "web" ]; then \
		flutter build web --release --web-renderer html $(F_FLAGS) $(args); \
	else \
		flutter build  $* --obfuscate --split-debug-info=. $(F_FLAGS) $(args); \
	fi


# -----------------------------------------------------------------------------
# OCI
# -----------------------------------------------------------------------------
#: build the image
oci:
	@$(foreach arch,$(ARCH), \
		version=$(shell echo $(VERSION) | sed -e 's/+.*//'); \
		echo "build: $(RELEASE_NAME):$${version}-$(arch)"; \
		podman build -t $(RELEASE_NAME):$${version}-$(arch) -f $(DOCKERFILE) \
			--arch $(arch) $(args) \
			--build-arg arch=$(arch) \
			--annotation org.opencontainers.image.created="$(shell date -I'seconds')" \
			--annotation org.opencontainers.image.description="$(DESCRIPTION)" \
			--annotation io.artifacthub.package.readme-url="$(README)"; \
	)

#: push an image to a specified location that defined in '.makerc'
oci-push:
ifdef REGISTRY_USER
	podman login -u $(REGISTRY_USER) -p $(REGISTRY_PWD) $(REGISTRY)
else
	podman login $(REGISTRY)
endif

	-podman manifest rm $(RELEASE_NAME):$(VERSION)
	podman manifest create $(RELEASE_NAME):$(VERSION)

	@$(foreach arch,$(ARCH), \
		echo "push: $(REGISTRY)/$(REGISTRY_REPO)/$(RELEASE_NAME):$(VERSION)-$(arch)"; \
		podman push $(RELEASE_NAME):$(VERSION)-$(arch) \
			$(REGISTRY)/$(REGISTRY_REPO)/$(RELEASE_NAME):$(VERSION)-$(arch); \
		podman manifest add $(RELEASE_NAME):$(VERSION) \
			$(REGISTRY)/$(REGISTRY_REPO)/$(RELEASE_NAME):$(VERSION)-$(arch); \
	)

	@echo "push: $(REGISTRY)/$(REGISTRY_REPO)/$(RELEASE_NAME):$(VERSION)"
	podman manifest push $(RELEASE_NAME):$(VERSION) $(REGISTRY)/$(REGISTRY_REPO)/$(RELEASE_NAME):$(VERSION)

# -----------------------------------------------------------------------------
# Helm
# -----------------------------------------------------------------------------
#: generate the Helm chart
helm:
	gkgen helm $(args)
ifneq ($(NAME),$(RELEASE_NAME))
	sed -i -e 's/name: $(NAME)/name: $(RELEASE_NAME)/' .chart/Chart.yaml
endif
	cp .config/service.k8s.yaml .chart/values.yaml
ifneq ($(wildcard .chart/Chart.lock),)
	rm .chart/Chart.lock
endif
	helm dependency build .chart/
	helm lint .chart/

#: render chart templates locally and write to '.chart/k8s.yaml'
pod: helm
	helm template $(RELEASE_NAME) .chart/ > .chart/k8s.yaml

#: upload chart to the repo that defined in '.makerc'
package: helm
	helm cm-push .chart/ $(HELM_REPO)

#: install the chart to a remote defined in '.makerc'
install:
	helm repo update && helm install $(RELEASE_NAME) $(HELM_REPO)/$(RELEASE_NAME) -n $(HELM_NAMESPACE) --version $(VERSION) $(args)

#: upgrade the release to the current version of the chart
upgrade:
	helm repo update && helm upgrade $(RELEASE_NAME) $(HELM_REPO)/$(RELEASE_NAME) -n $(HELM_NAMESPACE) --version $(VERSION) $(args)

#: restart the release
restart:
	kubectl rollout restart $(DEPLOYMENT_KIND)/$(RELEASE_NAME) -n $(HELM_NAMESPACE)

#: uninstall the release
uninstall:
	helm uninstall $(RELEASE_NAME) -n $(HELM_NAMESPACE)

#: execute the release
exec:
	kubectl exec -it $(DEPLOYMENT_KIND)/$(RELEASE_NAME) -n $(HELM_NAMESPACE) -- sh

#: print the logs for the deployment
logs:
	kubectl logs $(DEPLOYMENT_KIND)/$(RELEASE_NAME) -f -n $(HELM_NAMESPACE) --timestamps

#: stop the release
stop:
	kubectl scale --replicas=0 $(DEPLOYMENT_KIND)/$(RELEASE_NAME) -n $(HELM_NAMESPACE)
